FROM python:3.9-slim-buster

# Install git for adding dependecies from git
RUN apt-get update && apt-get -y install git

# Set working directory
WORKDIR /app

# Copy project file
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy all project
COPY . .

# Create package
RUN python setup.py sdist
