version: '3.3'

services:

  prometheus:
    image: prom/prometheus:latest
    # container_name: prometheus
    ports:
      - "9090:9090"

  pushgateway:
    image: prom/pushgateway:latest
    # container_name: pushgateway
    ports:
      - "9091:9091"
          