version: '3.3'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipservices/test}
    depends_on:
      - kafka
    environment:
      - KAFKA_SERVICE_HOST=kafka
      - KAFKA_SERVICE_PORT=9092
      - KAFKA_TOPIC=test
      - KAFKA_USER=kafka
      - KAFKA_PASS=pass123

  zookeeper:
    image: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_PORT=2181
      - ZOOKEEPER_SERVERS=server.1=zookeeper:2888:3888
      - ZOOKEEPER_SASL_ENABLED=false

  kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - './kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf'
    environment:
      - KAFKA_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ZOOKEEPER_SASL_ENABLED=false
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
      - KAFKA_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT
      - KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper